Repository c4coderandcreator/Flavour-Fusion, pull requests merged in 2023-10, with the labels that each got.

#17 [Added] Dark Theme Button and UI Changes.
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#31 amended typo on about section
  index.html
Labels: bug, hacktoberfest, hacktoberfest-accepted

#37 Feedback Page Added
  Feedback.html
  css/landing.css
  index.html
  vanilla-tilt.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Try-Out

#38 Minor UI change on the home page #19
  css/landing.css
  index.html
  vanilla-tilt.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#41 Changes done
  assets/order-history-image-landing.jpg
  assets/order-history-image-landing.png
  css/landing.css
  index.html
Labels: enhancement, question, hacktoberfest, hacktoberfest-accepted

#43 UI improvement
  Feedback.html
  assets/order-history-image-landing.jpg
  assets/order-history-image-landing.png
  css/landing.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#44 dynamic year for footer
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#53 Minor improvements
  assets/new-order-landing.png
  css/landing.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#60 changed navbar and updated order button
  css/landing.css
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#70 fix: Alignment Issue with Sign Up/Sign In Page Close Button
  CODE_OF_CONDUCT.md
  css/signInUp.css
  index.html
Labels: bug, hacktoberfest, hacktoberfest-accepted

#74 Converted button text to moving symbols (toggle button)
  CONTRIBUTING.md
  README.md
  css/landing.css
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#75 UI improvement
  css/landing.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#86 made the navbar responsive
  css/landing.css
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest-accepted

#89 UI improvement
  css/landing.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#91 Order section layout modified, 'Menu' with 'Search bar' on left and 'Your Cart' on right
  .github/ISSUE_TEMPLATE/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pull-request-template.md
  README.md
  SECURITY.md
  anorder.css
  anorder.js
  index.html
  order.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#95 home page redirect link update
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#100 Menu text legibility
  menu.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#105 Added hover effect in navbar-items and fixed a minor bug
  css/landing.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#112 UI improvement
  css/landing.css
  index.html
  menu.css
  order.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#115 fix: disable scroll y when sign in is on page
  javascript/signInUp.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Intermediate

#121 UI IMPROVEMENT LIST OF CAFES
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#124 UI improvement
  css/landing.css
  index.html
  menu.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#128 Update README.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#131 Fixed sign-in page animation
  README.md
  css/signInUp.css
  index.html
  javascript/signInUp.js
Labels: bug, enhancement, good first issue, hacktoberfest

#129 Update README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#133 UI improvement
  css/signInUp.css
  index.html
  javascript/signInUp.js
Labels: enhancement, good first issue, hacktoberfest

#135 added shadow in navbar
  README.md
  css/landing.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#138 UI improvement
  css/landing.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#154 fixed scroll issue in about section (#153)
  index.html
Labels: bug, enhancement, good first issue, hacktoberfest

#156 SEO improvement
  README.md
  css/landing.css
  css/signInUp.css
  index.html
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#158 Back button in track order
  index.html
  track-sam.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#163 Updated logo
  assets/flavorfusion-logo.png
  css/landing.css
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#165 Added "forgot password" to sign-in page and enhanced UI
  css/signInUp.css
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#170 Responsive Order section, Close button styling
  .DS_Store
  .vscode/settings.json
  index.html
  order.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#171 Order Back Button linked to Order instead of HomePage
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#172 Fixed dark theme issue in order tracking section
  .vscode/settings.json
  track-sam.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#174 UI improvement
  .vscode/settings.json
  track-sam.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#179 Menu items linked to order section
  index.html
  order.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#181 Like Counter
  README.md
  index.html
  menu.css
  menu.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#183 Fixed dark theme issue after reloading
  index.html
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#187 Fixed Redirection bug of Menu and About Section
  allindex.js
  menu.js
  order.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#188 feat: improve seo by adding important meta elements 🚀✨
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#192 UI changes
  css/landing.css
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#195 Added a Reservation Page
  css/landing.css
  css/reservation.css
  index.html
  reservation.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#200 Adding the Hovering Effect to Socials Links in the Footer Section
  css/allstyle.css
  css/landing.css
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#204 added order into the cart
  index.html
  order.css
  order.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Try-Out, Intermediate

#209 Spells and design
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#210 Made the Navbar responsive again
  css/landing.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#211 fixed header responsive issue (207)
  css/landing.css
Labels: hacktoberfest, hacktoberfest-accepted, Try-Out

#224 [feat]: dummy data User Feedback
  allindex.js
  index.html
  order.css
  order.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#233 Add more items to Soup Menu
  assets/soup/soup7.png
  assets/soup/soup8.png
  assets/soup/soup9.png
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#240 Added Facebook social login & optimized sign-up/sign-in prompts
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#244 fixed issue 242
  index.html
  reservation.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#252 Smaller UI-Improvements
  Resources/About-us-page/contentImg1.jpg
  Resources/About-us-page/contentImg2.jpg
  Resources/About-us-page/contentImg3.jpg
  assets/salmon-salad.png
  css/landing.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Intermediate

#260 Fixed & Enhanced the Footer section
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
